import pandas as pd
from sklearn import linear_model
import matplotlib.pyplot as plt

#read data
# x - polarity generated by Sentiment Analysis (TextBlob)
# y - rating given by various websites

dataframe = pd.read_fwf('movie_rating.txt')
x_values = dataframe[['polarity']]
y_values = dataframe[['rating']]

#train model on data
body_reg = linear_model.LinearRegression()
body_reg.fit(x_values, y_values)

#visualize results
plt.scatter(x_values, y_values)
plt.plot(x_values, body_reg.predict(x_values))
plt.show()